### PR TITLE
Slow image preview

### LINKED ISSUE #403: Slow Image Preview
I think image previews should use lower resolution renders for high megapixel captures. Forking it tomorrow.

### PR DESCRIPTION
**Pull request by dnalot**
Fix #403

### CODE REVIEW

**Comment by dnalot** [comment]
Not ready to merge yet. There's one timing bug due to promises not being cancelable. I'll get to it soon. Feedback welcome.

**Comment by dnalot** [comment]
Ready to test.

**Comment by lrsjng** [comment]
I started updating the image preview in https://github.com/lrsjng/h5ai/commit/686405142be421284e6978159646fff7d2eabb4c. Wanted to clean it up anyway.. should work as expected

**Comment by dnalot** [comment]
Does that mean I should rebase this branch on top of yours? Did you try this one? The last commit fixed a bug in `master`.

**Comment by dnalot** [comment]
The individual commits were intentionally incremental. Promises streamlined asynchronous reasoning which became necessarily more complex.

**Comment by lrsjng** [comment]
Tried all commits at once, and had problems, the previews did not always show up, spinner kept spinning..

**Comment by lrsjng** [comment]
my changes in `class-thumb.php` are the same as yours, just a little bit more verbose, my changes to `preview-img.js` differ from yours, wanted to avoid deferred objects here.. also added the "show thumb while waiting"-thing someone suggested..

**Comment by dnalot** [comment]
Why are you avoiding `Deffered`? The promise pattern is exactly this kind of asynchronous complexity. I can rebase but it's going to be a lot of work :cold_sweat:

**Comment by lrsjng** [comment]
I really like the concept of deferred objects and promises, I'm using it a lot in `fquery` and `mkr`, but in this case I decided to just flatten the functions, as deferreds will bring no real advantage here. I'm sorry, no bad intent..

**Comment by dnalot** [comment]
Mine is live [here](photo.dnalot.com). There's some advantage to not nesting functions arbitrarily deep. But it should simplify the first two requirements below (especially the first). Could you make an `image-preview` branch for me to rebase onto? What's left for you to implement is:
- [ ] Fix issue when user advances index faster than images load
- [ ] Load full-sized image after sampled preview (preferably without copy/paste)
- [ ] Duplication between `requestSample()` and `thumbnails.requestSample()` (I'm importing `thumbnails` instead of `server` but they could share a common `api` import)

**Comment by lrsjng** [comment]
photos.dnalot.com work like a charm for me :+1: 

> Fix issue when user advances index faster than images load

this should already be included

> Load full-sized image after sampled preview (preferably without copy/paste)

after visiting your site, I understand what you mean here. But (no offence here) I don't like that behaviour. I think the show-thumbnail-while-loading approach is clearer here, and less resource consuming. After all it's just a preview..

> Duplication between requestSample() and thumbnails.requestSample() (I'm importing thumbnails instead of server but they could share a common api import)

I noted that - my current aim is not to rely on files in the `ext`-folder (only exception at the moment should be the `preview-*` modules relying on `preview`, but that's a work in progress)

---

As for the branch I'm not sure what your intention is. Just branch before my commit in your fork?!?

**Comment by dnalot** [comment]
I assumed there were more commits coming. That way in case you work on something unrelated (like visual or code styling) then I wouldn't have to rebase them.

**Comment by dnalot** [comment]
I agree with the rest of what you said.

**Comment by dnalot** [comment]
> this should already be included

Works for me.

> I think the show-thumbnail-while-loading approach

I like how you applied the mask it's very clever.

**Pull request closed without merging**
